// Alle Kategorien und ihre Einträge.
// Neue Kategorie: einfach einen weiteren Block { name: '…', eintraege: [ … ] } anhängen.
// Die Reihenfolge hier ist egal – die App sortiert die Kategorien alphabetisch.

export const KATEGORIEN = [
  {
    name: 'Bar',
    eintraege: [
      'Ein Barhocker mit notdürftig geflicktem Kunstlederbezug',
      'Eine Flasche selbstgebrannter Kartoffelschnaps ohne Etikett',
      'Ein Dartboard, in dem ein Schraubenzieher steckt',
      'Eine Jukebox, die nur noch drei Lieder spielt – alle traurig',
      'Eine Kreidetafel mit den Schulden der Stammgäste',
      'Ein Glas eingelegter Eier, das Ablaufdatum ist unleserlich',
      'Eine Neonreklame für Bier, bei der zwei Buchstaben flackern',
      'Ein Kartenspiel, dem die Pik-Dame fehlt',
      'Ein Aschenbecher aus einem halbierten Kolbenkopf',
      'Ein Foto der Bowlingmannschaft von Schicht B an der Wand',
      'Eine Messingglocke über dem Tresen für „Runde aufs Haus“',
      'Ein Getränkeautomat, der nur noch lauwarme Zitronenlimo ausgibt',
      'Klebrige Bierdeckel mit notierten Durchwahlnummern',
      'Ein Röhrenfernseher mit Sportwiederholungen von der Erde',
      'Ein Schild: „Keine Waffen am Tresen – das gilt auch für dich, Hank“',
      'Ein Bartuch, das seit Wochen nicht gewaschen wurde',
      'Eine Stange synthetischer Zigaretten der Marke „Frontier“',
      'Ein kaputter Flipperautomat mit Weltraumpiraten-Motiv',
      'Ein Eimer unter einer tropfenden Kühlleitung',
      'Ein Flaschenöffner an einer Kette, festgeschweißt am Tresen',
      'Ein Glas voller Münzen aus allen möglichen Kolonien',
      'Ein Stapel Pokerchips aus mindestens drei verschiedenen Sets',
      'Ein handgemaltes Schild: „Happy Hour: nie“',
      'Eine zerkratzte Theke mit eingeritzten Initialen und Datumsangaben',
      'Ein Kühlschrank voller Dosenbier der Konzernmarke',
      'Ein ausgestopfter Fisch, der auf Knopfdruck singen sollte',
      'Ein Mixer, der nur noch auf höchster Stufe läuft',
      'Leere Flaschen, als Kerzenhalter zweckentfremdet',
      'Ein Armdrücktisch mit abgewetzten Handgriffen',
      'Ein vergilbtes Pin-up-Poster einer Frau im Raumanzug',
      'Eine winzige Bühne mit einem verstimmten Klavier',
      'Ein Karaoke-Mikrofon, mit Isolierband umwickelt',
      'Eine Wette auf einer Serviette: „Wer zuerst zurück zur Erde darf“',
      'Zerbrochenes Glas, das jemand unter einen Tisch gekehrt hat',
      'Ein Billardtisch, der deutlich schief steht',
      'Ein Queue, das jemand als Schiene für einen Arm benutzt hat',
      'Salzbrezeln in einer verbeulten Metallschüssel',
      'Eine Tafel mit dem Tagesgetränk: „Reaktorkern – nur ein Glas pro Person“',
      'Ein Deckenventilator, der den Rauch nur im Kreis dreht',
      'Ein vergessener Schutzhelm auf dem Tresen',
      'Eine Liste mit Trinkspielregeln, an die Wand genagelt',
      'Ein Spendenglas für die Familie eines verunglückten Minenarbeiters',
      'Eine Flasche echter Whiskey von der Erde, hinter Gittern verschlossen',
      'Ein Destillierapparat im Hinterzimmer, zusammengebaut aus Laborglas',
      'Ein Plastikflamingo auf dem Regal hinter der Bar',
      'Ein Wandkalender mit Motiven tropischer Strände',
      'Eine abgesägte Schrotflinte unter dem Tresen',
      'Eine Kiste mit Fundsachen – Handschuhe, Ausweise, ein Glasauge',
      'Ein Plattenspieler mit einer einzigen Country-Platte',
      'Kondenswasserringe auf jedem einzelnen Tisch',
      'Ein Pokal für den Sieger des Trinkwettbewerbs 2179',
      'Eine Hausverbotsliste mit Polaroidfotos',
      'Eiswürfel, die leicht nach Kühlmittel schmecken',
      'Eine Lichterkette, die das ganze Jahr hängt',
      'Ein alter Synthetik-Barkeeper, dessen Hand beim Einschenken zittert',
      'Eine Vitrine mit Abzeichen verschiedener Konzerne und Einheiten',
      'Ein Würfelbecher aus abgewetztem Leder',
      'Die zerschlissene Flagge einer längst aufgelösten Marineeinheit',
      'Eine Toilettentür mit Schild „Außer Betrieb seit Schicht 4“',
      'Getränkebons, die hier als Zweitwährung durchgehen',
      'Ein Stammtisch mit reservierten Namensschildern',
      'Ein Porzellanhund auf dem Tresen, dem ein Ohr fehlt',
      'Ein Fass mit selbstgebrautem Pilzbier',
      'Zitronenscheiben aus der Konservendose',
      'Eine Flasche Schnaps mit einem Wurm darin – angeblich nicht von der Erde',
      'Eine laminierte Getränkekarte mit Kaffeeflecken',
      'Ein Zapfhahn, der nur noch Schaum liefert',
      'Ein Münztelefon mit Verbindung zur Stationszentrale',
      'Eine sorgfältig beschriftete Muschelsammlung von der Erde',
      'Ein Grammophon mit Trichter, das tatsächlich funktioniert',
      'Eine Anzeigetafel: „Tage ohne Schlägerei: 0“',
      'Ein Spielautomat, der angeblich noch nie ausgezahlt hat',
      'Ein Barhocker, auf den sich niemand setzen will',
      'Schwarzmarkt-Zigarren in einer Keksdose',
      'Ein Rekrutierungsposter: „Sieh die Sterne! Verpflichte dich!“',
      'Ein Stapel zerlesener Klatschmagazine von der Erde',
      'Eine fast leere Flasche Blutorangenlikör',
      'Ein Pfandbuch mit verpfändeten Armbanduhren und Eheringen',
      'Eine Discokugel, der die Hälfte der Spiegel fehlt',
      'Ein Schnapsglas mit einem Zahn darin',
      'Das Namensschild eines Barkeepers, der „vor zwei Monaten gegangen“ ist',
      'Ein Wasserkocher für heißen Grog',
      'Sägespäne auf dem Boden gegen verschüttetes Bier',
      'Ein handgemaltes Wandbild einer Bergwiese mit Kühen',
      'Ein verbeulter Cocktailshaker',
      'Modelle von Frachtschiffen in Flaschen',
      'Ein Hinterzimmer mit Pokertisch unter einer grünen Lampe',
      'Ein Kaugummiautomat, gefüllt mit Schrauben statt Kaugummis',
      'Eine Flasche „Medizinischer Alkohol“ mit handschriftlichem Barpreis',
      'Ein Schild: „Synthetische werden hier nicht bedient“',
      'Ein Rauchmelder, mit einer Plastiktüte abgeklebt',
      'Ein Radio, das den Funkverkehr vom Landefeld mithört',
      'Ein Drink auf dem Tresen, der offenbar nie abgeholt wurde',
      'Ein einzelner Stiefel unter dem Tresen – ohne Besitzer',
      'Eine Sammlung von Feuerzeugen verstorbener Stammgäste',
      'Eine Pyramide aus leeren Bierdosen',
      'Ein Pinnbrett mit Jobangeboten: „Bohrcrew gesucht, keine Fragen“',
      'Ein Zettel: „Suche Mitfahrgelegenheit zum nächsten Hub, zahle gut“',
      'Ein Wischmopp, der nach Essig riecht',
      'Eine Tafel mit Wetten, wann der nächste Sturm kommt',
    ],
  },
  {
    name: 'Buchtitel',
    eintraege: [
      'Die Kälte zwischen den Sternen',
      'Handbuch für Hydrauliksysteme, 7. Auflage',
      'Schlaf ist optional – Produktivität im Kälteschlafzyklus',
      'Die Witwe von Kolonie Sieben',
      'Mein Leben als Frachtpilot',
      'Ferne Ufer, rote Monde',
      'Atmosphärenaufbereitung für Einsteiger',
      'Der letzte Zug nach Terra',
      'Einsamkeit und Vakuum – Gedichte',
      'Kochen mit Proteinriegeln',
      'Das Geheimnis von Station Kerberos',
      'Nachtschicht',
      'Tödliche Fracht',
      'Vertragsrecht im Äußeren Rand',
      'Kinder der Leere',
      'Überleben in feindlichen Umgebungen – Offizielles Handbuch',
      'Die Farbe des Rosts',
      'Liebe in der Schwerelosigkeit',
      'Staub über den Ebenen',
      'Grundlagen der Exobiologie, Band 2',
      'Kleine Reparaturen am Frachter',
      'Der Mann, der nicht aufwachte',
      'Anleitung zum Bergbau auf Asteroiden',
      'Arbeitssicherheit – Konzernausgabe für Angestellte',
      'Wenn die Sirenen heulen',
      'Tagebuch eines Kolonisten',
      'Der Himmel über Vesta Prime',
      'Schach für Fortgeschrittene',
      'Das Evangelium des Äußeren Rands',
      'Die Rückkehr des Kapitäns',
      'Kreuzworträtsel, Band 14',
      'Psychologie der Isolation',
      'Eine kurze Geschichte der Handelsrouten',
      'Die schwarze Kammer',
      'Märchen von der alten Erde',
      'Söldnerherz',
      'Drei Jahre im Kälteschlaf',
      'Einführung in die Fusionstechnik',
      'Die Frau am Ende des Korridors',
      'Rote Lichter, lange Gänge',
      'Das große Buch der Knoten',
      'Mondsucht',
      'Dienstvorschrift 12-B: Verhalten bei Quarantäne',
      'Eine abgegriffene Bibel mit Notizen am Rand',
      'Wie man Freunde gewinnt – auch im Exil',
      'Der Schatten im Frachtraum',
      'Die Sterne gehören uns',
      'Unter dem Eis',
      'Gärtnern in Hydrokultur',
      'Tausend Arten zu schweigen',
      'Handbuch der Notfallmedizin',
      'Das Erbe der Gründer',
      'Stahlwüste',
      'Lieder der Minenarbeiter',
      'Das Ding aus dem Nebel',
      'Fernmeldetechnik kompakt',
      'Hoffnung ist ein Luxusartikel',
      'Die Kunst, Vorgesetzte zu überleben',
      'Der Konzern – eine autorisierte Biografie',
      'Sturmwarnung',
      'Leitfaden für den Umgang mit Synthetischen',
      'Die neunte Schicht',
      'Lügen für Fortgeschrittene',
      'Frachtbrief ins Nirgendwo',
      'Das Haus am See',
      'Pflanzen der alten Erde – ein Bildband',
      'Rotationsschwerkraft verständlich erklärt',
      'Blut auf dem Deck',
      'Der Pilot und das Mädchen',
      'Einmal Hölle und zurück',
      'Ersatzteilkatalog, Serie 400',
      'Grenzland',
      'Der Tag, an dem die Funkstille begann',
      'Jenseits der Heliopause',
      'Kalte Hände, warmes Herz',
      'Befragungstechniken für Sicherheitspersonal',
      'Die dunkle Seite des Mondes',
      'Ratgeber: Gelassen bleiben unter Druck',
      'Zwischen den Welten',
      'Die Nacht der Maschinen',
      'Bauernkalender der Kolonie Neu-Kansas',
      'Die verlorene Expedition',
      'Wie ich lernte, die Stille zu lieben',
      'Hochzeit auf dem Frachtdeck',
      'Der lange Abstieg',
      'Sprachführer Japanisch für Konzernangestellte',
      'Die Krankheit der Sterne',
      'Tiefsee, Tiefraum',
      'Die zwölf Tore',
      'Karten des bekannten Raums (veraltete Ausgabe)',
      'Der Duft der Heimat',
      'Mord auf Station Nadir',
      'Rezepte meiner Großmutter',
      'Taktik für kleine Einheiten',
      'Das stille Signal',
      'Ein Sommer in Ohio',
      'Asche und Eis',
      'Letzte Worte berühmter Raumfahrer',
      'Die Stimme im Lüftungsschacht',
      'Parasiten der tropischen Zonen',
    ],
  },
  {
    name: 'Büro',
    eintraege: [
      'Ein Ventilator auf dem Aktenschrank, der nur noch quietscht',
      'Ein Terminal mit grünem Monochrombildschirm und blinkendem Cursor',
      'Ein Stapel ausgedruckter Frachtmanifeste',
      'Ein Wandkalender, seit drei Monaten nicht umgeblättert',
      'Eine Kaffeetasse mit der Aufschrift „Bester Schichtleiter“',
      'Ein Aktenschrank mit einer verbogenen Schublade, die klemmt',
      'Ein Faxgerät, das ab und zu von selbst anspringt',
      'Eine Pinnwand voller Sicherheitsvorschriften',
      'Ein Poster: „Ihre Sicherheit ist unser höchstes Gut – Ihr Konzern“',
      'Eine vertrocknete Topfpflanze',
      'Ein Drehstuhl mit durchgesessenem Polster',
      'Stempel: „GENEHMIGT“, „ABGELEHNT“ und „VERTRAULICH“',
      'Ein Papierkorb voller zerknüllter Briefentwürfe',
      'Eine Rohrpoststation mit einer steckengebliebenen Kapsel',
      'Ein Schwarzes Brett mit Schichtplänen',
      'Zwei Wanduhren: Erdzeit und Stationszeit',
      'Ein Aschenbecher voller Kippen, obwohl Rauchen verboten ist',
      'Ein Tischventilator mit flatternden Papierstreifen am Gitter',
      'Ein Aktenordner: „Zwischenfälle – nicht weitergeleitet“',
      'Eine Wandkarte der Kolonie mit farbigen Stecknadeln',
      'Ein blubbernder Wasserspender',
      'Ein Drucker, der seit Wochen „Papierstau“ meldet',
      'Ein umgedrehtes Namensschild auf dem Schreibtisch',
      'Ein Kopierer, der auf jede Kopie denselben Fleck druckt',
      'Ein Wandtresor hinter einem Landschaftsgemälde',
      'Ein „Mitarbeiter des Monats“-Foto mit ausgekratzten Augen',
      'Eine Sprechanlage zur Stationszentrale',
      'Eine Wanduhr, die ständig nachgeht',
      'Jalousien vor einem Fenster, das nur auf eine Stahlwand zeigt',
      'Ein Stapel unbeantworteter Beschwerden',
      'Eine akribisch geführte Überstundenliste',
      'Ein Diktiergerät mit halb bespieltem Band',
      'Ein veralteter Fluchtwegeplan',
      'Eine Trennwand, beklebt mit Kinderzeichnungen',
      'Ein Karteikasten mit Personalakten',
      'Ein Sofa, auf dem offensichtlich jemand übernachtet hat',
      'Eine Schreibtischlampe mit grünem Glasschirm',
      'Ein Zettel: „Besprechung verschoben – schon wieder“',
      'Ein Briefbeschwerer aus Meteoritengestein',
      'Ein rot eingekreistes Datum im Kalender: „Ablösung“',
      'Ein Tischtelefon mit vielen Tasten, von denen nur zwei funktionieren',
      'Eine tropfende Klimaanlage',
      'Ein Aktenvernichter mit einem halb zerschnittenen Dokument',
      'Eine Tafel: „Tage ohne Arbeitsunfall: 3“',
      'Ein Karton mit den persönlichen Sachen eines entlassenen Mitarbeiters',
      'Ein Schlüsselbrett, an dem drei Schlüssel fehlen',
      'Ein Organigramm, in dem ein Name durchgestrichen ist',
      'Eine verstaubte Plastikpflanze',
      'Eine Tafel mit Förderzahlen, die rot markiert sind',
      'Ein Monitor mit Überwachungsbildern leerer Gänge',
      'Ein Stapel Formulare in dreifacher Ausfertigung',
      'Kaffeeringe auf dem Schreibtisch, die fast eine Landkarte bilden',
      'Die offene Tür zum Chefbüro mit Ledersessel',
      'Eine Rollkartei mit Kontakten auf drei Planeten',
      'Ein Poster mit einem Kätzchen an einem Ast: „Halte durch!“',
      'Eine Stempeluhr mit Stechkarten',
      'Ein Tischkalender mit durchgestrichenen Tagen',
      'Eine Gegensprechanlage, aus der leises Rauschen kommt',
      'Ein zugeschweißter Kummerkasten',
      'Eine leere Geldkassette',
      'Eine flackernde Leuchtstoffröhre',
      'Postfächer mit Nachrichten, die nie abgeholt wurden',
      'Ein Regal mit Konzernhandbüchern in identischen Einbänden',
      'Ein Golfputter und ein Plastikbecher als Loch',
      'Eine Wanduhr mit der Aufschrift „Zeit ist Geld“',
      'Ein verschlossener Schrank mit Aufkleber „Nur Management“',
      'Ein halber Donut auf einem Aktenordner',
      'Das Terminalpasswort auf einem Klebezettel am Bildschirm',
      'Eine Milchglastür mit aufgedrucktem Namen und Titel',
      'Ein Gummibaum, der erstaunlich gut gedeiht',
      'Ein Stapel Umschläge für die Post zur Erde',
      'Eine Sammlung von Werbekugelschreibern',
      'Ein Warnschild: „Vertrauliche Unterlagen – Zutritt nur mit Freigabe“',
      'Ein Foto vom Firmenpicknick auf der Erde, vor vielen Jahren',
      'Ein Bildschirmschoner mit rotierendem Konzernlogo',
      'Ein Heizkörper, der ständig klopft',
      'Ein Fußabtreter vor dem Chefbüro: „Willkommen“',
      'Ein Stuhl, auf dem ein Aktenstapel als Sitzkissen dient',
      'Ein Fernschreiber, der gerade eine Nachricht ausspuckt',
      'Ein halb geplünderter Erste-Hilfe-Kasten',
      'Eine Bürotrennwand mit zwei Einschusslöchern',
      'Ein Aktenwagen mit quietschendem Rad',
      'Eine verstaubte Auszeichnung für „Herausragende Effizienz“',
      'Ein Terminal mit einer ungelesenen Nachricht der Priorität 1',
      'Ein Tischkicker in der Ecke',
      'Eine penibel geführte Liste über den Verbrauch von Büroklammern',
      'Ein Kleiderständer mit einem einzelnen Laborkittel',
      'Ein Rauchmelder ohne Batterie',
      'Ein Wandtresor, dessen Tür offen steht',
      'Unterschriebene Kündigungsschreiben, nie abgeschickt',
      'Eine Weltkarte der Erde mit handschriftlichen Reisezielen',
      'Ein Tischventilator mit notdürftig geflicktem Kabel',
      'Ein Magnetbandlaufwerk mit einem Band im Einzug',
      'Ein kleines Konzernfähnchen auf dem Schreibtisch',
      'Ein Block mit Durchschlagpapier',
      'Ein Aquarium ohne Fische, das Wasser ist grün',
      'Eine Rohrleitung, die quer durch das Büro verläuft und leise gluckert',
      'Ein Aufkleber am Terminal: „NICHT AUSSCHALTEN!!!“',
      'Ein Besucherstuhl, der am Boden festgeschraubt ist',
      'Eine Namensliste mit Kreuzen hinter manchen Einträgen',
    ],
  },
  {
    name: 'Gegenstände',
    eintraege: [
      'Eine Taschenlampe mit schwacher Batterie, die man schütteln muss',
      'Ein schwerer Schraubenschlüssel mit eingraviertem Namen',
      'Eine halbe Rolle silbernes Klebeband',
      'Ein Sturmfeuerzeug mit dem Wappen einer Marineeinheit',
      'Eine verbeulte Thermoskanne mit lauwarmem Kaffee',
      'Eine Magnetkarte mit dem Foto eines Fremden',
      'Ein Brecheisen mit getrocknetem Blut am Ende',
      'Eine Signalfackel, abgelaufen, aber vermutlich noch brauchbar',
      'Ein alter Kompass, der auf diesem Planeten nutzlos ist',
      'Ein Handfunkgerät mit gebrochener Antenne',
      'Ein Erste-Hilfe-Kasten mit nur noch einem Verband',
      'Ein Blister Schmerztabletten, zwei Stück übrig',
      'Ein Taschenmesser mit sieben Funktionen, davon eine abgebrochen',
      'Zehn Meter Nylonseil mit Karabiner',
      'Ölverschmierte Arbeitshandschuhe',
      'Eine Schutzbrille mit zerkratzten Gläsern',
      'Eine Atemmaske mit halb verbrauchtem Filter',
      'Eine kleine Sauerstoffkartusche, noch zu einem Drittel voll',
      'Ein Handschweißgerät mit fast leerer Gaspatrone',
      'Ein Multimeter mit gesprungenem Display',
      'Eine Handvoll Kabelbinder',
      'Eine Schachtel Ersatzsicherungen',
      'Eine Notration: „Hackbraten mit Soße“, drei Jahre über dem Datum',
      'Eine Feldflasche mit abgestandenem Wasser',
      'Ein Kartenspiel mit Pin-up-Motiven',
      'Eine Mundharmonika in C-Dur',
      'Ein tragbarer Kassettenspieler mit Kopfhörern',
      'Eine Kassette, beschriftet: „Für Mia – nicht vor dem 12. anhören“',
      'Ein zerknicktes Foto eines lachenden Paares am Strand',
      'Eine Erkennungsmarke an einer Kugelkette',
      'Ein Ehering mit Gravur: „Bis ans Ende“',
      'Eine mechanische Armbanduhr, stehengeblieben um 3:17 Uhr',
      'Eine Baseballkappe mit Konzernlogo',
      'Eine kleine Plastikfigur eines Astronauten',
      'Ein Schlüsselbund mit elf Schlüsseln und einem Flaschenöffner',
      'Ein Werkzeuggürtel mit fehlendem Hammer',
      'Eine Dose Fleischkonserve ohne Etikett',
      'Eine zerdrückte Packung Zigaretten, noch drei drin',
      'Ein Flachmann mit billigem Wodka',
      'Ein kleines Notizbuch, in dem die letzten Seiten herausgerissen sind',
      'Ein Klemmbrett mit einer Inventarliste',
      'Ein Bolzenschneider',
      'Eine Nagelpistole mit halbvollem Magazin',
      'Eine Signalpistole mit einer Patrone',
      'Drei grüne Leuchtstäbe',
      'Ein tragbarer Bewegungsscanner, der manchmal Geisterpunkte zeigt',
      'Ein Geigerzähler, der leise tickt',
      'Ein Datenband mit der Aufschrift „Backup 3/7“',
      'Eine Einwegspritze, originalverpackt',
      'Ein Nähset in einer Blechdose',
      'Eine Schachtel Streichhölzer von einer Bar in Neu-Houston',
      'Ein Seesack voller Wäsche',
      'Ein Taschenrechner mit Solarzelle',
      'Ein Fernglas mit einem kaputten Okular',
      'Eine Tabakspfeife mit abgebissenem Mundstück',
      'Eine Dose Kautabak',
      'Ein Schokoriegel, geschmolzen und wieder fest geworden',
      'Ein abgewetzter Teddybär mit nur einem Knopfauge',
      'Ein aufziehbarer Spielzeugroboter',
      'Ein Rosenkranz aus Holzperlen',
      'Eine Hasenpfote als Glücksbringer',
      'Zwei Würfel, einer davon offensichtlich gezinkt',
      'Ein Geduldspiel aus Metall',
      'Eine kleine Hantel, fünf Kilo',
      'Ein Nassrasierer und eine stumpfe Klinge',
      'Eine Brille mit gesprungenem Glas',
      'Ein einzelner Babyschuh',
      'Eine Haarspange in Form eines Sterns',
      'Ein Lippenstift in knalligem Rot',
      'Ein fast leerer Parfümflakon',
      'Ein Taschenspiegel mit einem Sprung',
      'Ein Fotoalbum mit Bildern von der Erde',
      'Ein Liebesbrief, nie abgeschickt',
      'Ein Walkie-Talkie, das nur Rauschen empfängt',
      'Eine zusammengefaltete Plastikplane',
      'Eine Rohrzange',
      'Ein Kanister mit fünf Litern Treibstoff',
      'Eine Sprühdose mit roter Farbe',
      'Ein Schutzhelm mit Stirnlampe',
      'Ein Klappspaten',
      'Eine goldene Rettungsdecke, noch verpackt',
      'Ein Probenbehälter mit Schraubdeckel, leer',
      'Ein Handscanner für Frachtetiketten',
      'Ein Gasfeuerzeug, das nur jedes dritte Mal zündet',
      'Eine Rolle Draht',
      'Ein Kästchen mit Ersatzbatterien, die Hälfte leer',
      'Eine verrostete Machete',
      'Eine Plastikflasche mit Desinfektionsmittel',
      'Ein Gummiknüppel eines Sicherheitsdienstes',
      'Eine Zugangskarte mit Magnetstreifen, leicht verbogen',
      'Ein Paar Handschellen ohne Schlüssel',
      'Ein Mikroskop-Objektträger mit einem dunklen Fleck',
      'Ein Handbohrer mit Akkupack',
      'Ein Dosenöffner vom Militär',
      'Eine Pillendose mit unbeschrifteten weißen Tabletten',
      'Ein Kamm mit abgebrochenen Zinken',
      'Ein abgenutzter Tennisball',
      'Eine Packung Kaugummi mit Zimtgeschmack',
      'Ein Nachtsichtgerät, das nur noch in Schwarz-Weiß zeigt',
      'Eine Tüte Kaffeebohnen, als Tauschware in Folie eingeschweißt',
    ],
  },
  {
    name: 'Gerüche',
    eintraege: [
      'Verschmorte Kabelisolierung',
      'Ozon, wie nach einem Blitzeinschlag',
      'Heißes Maschinenöl',
      'Süßliches Kühlmittel',
      'Feuchter Schimmel hinter der Wandverkleidung',
      'Alter, kalter Schweiß',
      'Abgestandener Kaffee, der zu lange auf der Heizplatte stand',
      'Kalter Zigarettenrauch in Stoffpolstern',
      'Scharfes Desinfektionsmittel',
      'Rost und nasses Metall',
      'Blut – kupfrig und schwer',
      'Verbranntes Haar',
      'Urin in einer Ecke',
      'Erbrochenes, notdürftig weggewischt',
      'Verwesung, schwach, aber unverkennbar',
      'Schwefel, wie faule Eier',
      'Stechender Ammoniak',
      'Nasser Hund',
      'Frisch gebackenes Brot – völlig unerwartet',
      'Heißer Kunststoff',
      'Verbrannter Gummi',
      'Raketentreibstoff',
      'Dieselabgase',
      'Batteriesäure',
      'Chlor wie in einem Schwimmbad',
      'Lötzinn und Flussmittel',
      'Staub, der auf heißen Lampen verbrennt',
      'Billiger Raumduft „Bergkiefer“',
      'Billiges, süßes Parfüm',
      'Herbes Rasierwasser',
      'Kernseife',
      'Waschmittel und feuchte Wäsche',
      'Alte Socken',
      'Überreifer Käse',
      'Saure Milch',
      'Angebranntes Essen',
      'Gebratene Zwiebeln',
      'Knoblauch, sehr viel Knoblauch',
      'Curry und Kreuzkümmel',
      'Altes Frittierfett',
      'Popcorn mit Butteraroma',
      'Karamellisierter Zucker',
      'Hochprozentiger Alkohol',
      'Verschüttetes, abgestandenes Bier',
      'Rauchiger Whisky',
      'Süßer Pfeifentabak',
      'Süßlicher, harziger Rauch einer illegalen Zigarette',
      'Weihrauch',
      'Kerzenwachs',
      'Altes Leder',
      'Neuer Teppichboden und Lösungsmittel',
      'Frische Farbe',
      'Industriekleber',
      'Formaldehyd',
      'Äther',
      'Latexhandschuhe',
      'Talkumpuder',
      'Sterile Krankenstation',
      'Kampfer und Wundsalbe',
      'Pfefferminz',
      'Eukalyptus',
      'Feuchte Erde und Moos aus der Hydrokultur',
      'Scharfer Flüssigdünger',
      'Gärender Kompost',
      'Salzwasser – wie am Meer',
      'Regen auf warmem Asphalt – eine Erinnerung an die Erde',
      'Tierstall',
      'Fauliger Fisch',
      'Algen und Brackwasser',
      'Sumpfgas',
      'Methan',
      'Abwasser aus einem Leck in der Kanalisation',
      'Heißer Staub aus dem Lüftungsschacht',
      'Gegrilltes Fleisch',
      'Zimt und Nelken',
      'Frische Orangen',
      'Vanille',
      'Frisch gemahlener Kaffee',
      'Schwarzer Tee',
      'Heißer Kakao',
      'Zitronenreiniger',
      'Bleiche',
      'Essig',
      'Nasser Beton',
      'Pulverdampf nach Schüssen',
      'Heißes Eisen',
      'Kalter Brandgeruch in verrußten Wänden',
      'Stechende Säure, die in der Nase brennt',
      'Ein unbekannter, süßlich-fauliger Geruch',
      'Mottenkugeln',
      'Altes Papier und Staub',
      'Kopiertoner',
      'Neues Plastik, frisch ausgepackt',
      'Babypuder',
      'Fieberschweiß eines Kranken',
      'Angstschweiß',
      'Verbrannte Elektronik mit beißendem Nachgeschmack',
      'Nasse Wolle',
      'Frisch gemähtes Gras – vermutlich aus einer Duftpatrone',
      'Nasses Fell und etwas Saures, das man nicht zuordnen kann',
    ],
  },
  {
    name: 'In Schreibtischschubladen',
    eintraege: [
      'Eine Handvoll Büroklammern, zu einer Kette verbunden',
      'Ausgeleierte Gummibänder',
      'Eine angebrochene Packung Zigaretten',
      'Ein Flachmann mit einem Rest Brandy',
      'Eine Pistole mit leerem Magazin',
      'Eine Pillendose mit Schlaftabletten',
      'Ein Schlüssel, der zu keinem bekannten Schloss passt',
      'Ein gerahmtes Familienfoto, mit der Bildseite nach unten',
      'Unterschriebene Scheidungspapiere',
      'Eine Packung Kondome, abgelaufen',
      'Ein angebissener Schokoriegel',
      'Ein Stapel Visitenkarten eines Handelsvertreters',
      'Ein Brief von der Erde, mehrfach gelesen',
      'Ein Notizzettel mit Zahlenkombinationen',
      'Ein ausgetrocknetes Stempelkissen',
      'Ein Hefter ohne Klammern',
      'Eine Kassette ohne Beschriftung',
      'Eine große Dose Kopfschmerztabletten',
      'Magentabletten, fast aufgebraucht',
      'Ein Nagelknipser',
      'Ein Haargummi mit einem langen roten Haar',
      'Zahnseide',
      'Pfefferminzbonbons, zusammengeklebt',
      'Eine Lesebrille in einem Etui',
      'Ein Lineal mit Konzernlogo',
      'Bleistiftstummel und ein Anspitzer',
      'Ein Fläschchen Korrekturflüssigkeit, eingetrocknet',
      'Briefmarken der Erdpost',
      'Ein Lottoschein, nie eingelöst',
      'Ein Wettschein für ein Rennen auf der Erde',
      'Ein zerlesenes Herrenmagazin',
      'Ein Comicheft: „Captain Comet und die Weltraumpiraten“',
      'Ein halb gelöstes Kreuzworträtsel',
      'Ein Reiseprospekt für eine Kreuzfahrt zu den Saturnringen',
      'Ein Schuldschein über 200 Credits nach einer Pokerrunde',
      'Geldscheine einer fremden Kolonialwährung',
      'Die Zugangskarte eines anderen Mitarbeiters',
      'Die Kopie einer fremden Personalakte',
      'Eine Gehaltsabrechnung mit hohen Abzügen',
      'Eine schriftliche Abmahnung wegen „Insubordination“',
      'Ein Beförderungsschreiben, nie ausgehändigt',
      'Eine Kinderzeichnung: „Papa auf dem Mond“',
      'Eine Haarlocke in einem Umschlag',
      'Eine stehengebliebene Armbanduhr',
      'Ein Diktierband mit der Aufschrift „Aussage – privat“',
      'Eine Datendiskette: „NICHT LÖSCHEN“',
      'Eine lose Schraube, sorgfältig aufbewahrt',
      'Ein Kabel ohne erkennbaren Zweck',
      'Eine kleine Taschenlampe',
      'Ein Streichholzbriefchen einer Bar',
      'Eine Serviette mit Lippenstiftabdruck und Telefonnummer',
      'Ketchuppäckchen aus der Kantine',
      'Zuckertütchen, ein ganzer Haufen',
      'Einzelne Teebeutel',
      'Ein Glas Instantkaffee',
      'Plastikbesteck',
      'Ein verschimmeltes Sandwich',
      'Ein unter die Schublade geklebter Kaugummi',
      'Ein Schraubenzieher mit gelbem Griff',
      'Ein Klappmesser',
      'Eine Dose Pfefferspray',
      'Ein Schlagring',
      'Lose Munition, verschiedene Kaliber',
      'Eine Medaille in einer Schachtel',
      'Ein Tagebuch mit kleinem Schloss',
      'Ein Stationsplan mit handschriftlichen Notizen',
      'Eine Karte der Umgebung mit einem roten Kreuz',
      'Nikotinpflaster',
      'Eine Blutprobe in einem Röhrchen, unbeschriftet',
      'Ein einzelner menschlicher Zahn',
      'Ein Zettel aus einem Glückskeks: „Du wirst eine weite Reise machen“',
      'Ein Radiergummi in Form eines Raumschiffs',
      'Ein Taschenrechner, dem die Taste „7“ fehlt',
      'Ein Stapel Briefumschläge, alle schon zugeklebt',
      'Ein Adressbuch, in dem viele Namen durchgestrichen sind',
      'Eine Pistolenschachtel, leer, aber mit Waffenöl verschmiert',
      'Ein Reserveschlüssel für den Waffenschrank',
      'Eine Liste: „Dinge, die ich ihr sagen will“',
      'Ein vergilbter Zeitungsausschnitt über ein Grubenunglück',
      'Ein Kartenspiel in einer Plastikhülle',
      'Ein Paar Würfel',
      'Eine Rolle Klebeband',
      'Ein Tintenfüller mit Goldfeder',
      'Eine Sonnenbrille, obwohl es hier keine Sonne gibt',
      'Eine Packung Beruhigungsmittel mit Rezept auf fremden Namen',
      'Eine Kassette mit der Aufschrift „Mixtape Sommer 79“',
      'Ein kleiner Kaktus in einem Joghurtbecher',
      'Ein Fläschchen Nagellack',
      'Ein Gebiss in einem Plastikbecher',
      'Ein Umschlag mit Bargeld und dem Wort „Schweigen“',
      'Eine Liste mit Schichtzeiten, bei der eine Person markiert ist',
      'Ein Klebezettel: „Nicht der Zentrale melden!“',
      'Ein Ausweis mit einem Foto, das ausgekratzt wurde',
      'Eine Mikrokassette aus einem Überwachungsgerät',
      'Ein Tütchen mit Samen: „Tomaten, Erde“',
      'Eine Schachtel mit Konzernanstecknadeln für Dienstjubiläen',
      'Ein Schraubglas mit Knöpfen',
      'Ein Kalender vom letzten Jahr',
      'Ein Kündigungsschreiben ohne Unterschrift',
      'Ein Foto eines Hundes mit der Aufschrift „Rex, 2169“',
    ],
  },
  {
    name: 'Kantine',
    eintraege: [
      'Ein Tablett mit grauem Proteinbrei, der leicht nach Nüssen schmeckt',
      'Automatenkaffee, der nach Pappe schmeckt',
      'Ein Speiseplan: „Montag: Fleischersatz. Dienstag: Fleischersatz.“',
      'Eine lange Schlange vor der Essensausgabe',
      'Gestapelte, noch feuchte Plastiktabletts',
      'Besteck, das an den Tischen angekettet ist',
      'Salz- und Pfefferstreuer, beide mit Salz gefüllt',
      'Ein Ketchupspender, der nur noch spritzt',
      'Grüner Wackelpudding mit undefinierbaren Stücken',
      'Kartoffelpüree aus der Pulvertüte',
      'Algenbrot mit grünlicher Kruste',
      'Schokopudding mit Haut obendrauf',
      'Pfirsiche aus der Dose',
      'Ein Korb mit echten Äpfeln – streng rationiert',
      'Rührei aus Eipulver',
      'Gebackene Bohnen mit Würstchen',
      'Chili con Carne mit Sojawürfeln',
      'Eine undefinierbare braune Suppe',
      'Verkochte Nudeln mit Tomatensoße',
      'Klebriger Reis mit Sojasoße',
      'Maiskolben aus der Hydrokultur – eine Seltenheit',
      'Ein Sojaburger mit welkem Salatblatt',
      'Fischstäbchen, die nie einen Fisch gesehen haben',
      'Hotdogs, die schon seit Stunden im Wasser liegen',
      'Pizzafreitag – der Höhepunkt der Woche',
      'Die Reste eines Geburtstagskuchens mit halb gegessener Glasur',
      'Eine riesige Kaffeemaschine, die blubbert und zischt',
      'Ein Teeautomat, der immer zu heißes Wasser ausgibt',
      'Milchpulver in einer großen Dose',
      'Ein Snackautomat mit einem steckengebliebenen Schokoriegel',
      'Am Boden festgeschraubte Tische und Bänke',
      'Ein Fernseher an der Wand, der Konzernnachrichten zeigt',
      'Ein Schild: „Tablett bitte zurückbringen – das gilt für ALLE“',
      'Ein überquellender Mülleimer',
      'Eine Durchreiche zur Küche mit einer Klingel',
      'Ein leerer Serviettenspender',
      'Ketchupflecken an der Decke – niemand weiß, wie',
      'Eine Kakerlake – wie ist die bloß hierher gekommen?',
      'Plastiktischdecken mit Karomuster',
      'Girlanden von der letzten Feier, halb abgerissen',
      'Ein lautstarker Streit um die letzte Portion Nachtisch',
      'Essensmarken, die unter der Hand getauscht werden',
      'Ein Aushang zur Rationierung: „Ab sofort nur noch ein Kaffee pro Schicht“',
      'Eine Kühltheke, deren Licht flackert',
      'Eine Salatbar mit welkem Salat und wässrigen Tomaten',
      'Ein tropfender Wasserhahn am Getränkespender',
      'Gläser mit Kalkflecken',
      'Ein Ecktisch, an dem immer dieselbe Clique sitzt',
      'Ein einsamer Mitarbeiter, der mit seinem Essen spricht',
      'Ein Radio, das Musik von vor zwanzig Jahren spielt',
      'Ein schwarzes Brett mit Tauschangeboten',
      'Eine Kiste mit Obstkonserven, alle verbeult',
      'Ein Topf mit Haferbrei, der seit dem Morgen warm gehalten wird',
      'Instantnudeln, die jemand heimlich mitgebracht hat',
      'Erdnussbutter in Portionspackungen',
      'Weißbrot in Scheiben, luftig und geschmacklos',
      'Ein Glas Senf, von dem keiner weiß, wem es gehört',
      'Ein Pfannkuchenstapel am Sonntag',
      'Grünes Getränkepulver mit „Vitaminen“',
      'Frittierte Kartoffelwürfel',
      'Ein Fleischlaib mit brauner Soße',
      'Kekse in Plastikfolie, drei Stück pro Person',
      'Eine Obstschale mit einer einzigen Banane',
      'Ein Tisch mit Wimpeln der Bergbaumannschaft',
      'Eine Kaffeetasse mit einem eingeritzten Namen',
      'Ein Tablett, das sich klebrig anfühlt',
      'Ein kaputter Stuhl, der seit Monaten in der Ecke steht',
      'Ein Streit über den Fernsehsender',
      'Eine Kantinenhilfe mit Haarnetz, die nie lächelt',
      'Ein Tellerwagen, der beim Schieben scheppert',
      'Ein Warnschild: „Rutschgefahr“ neben einer Pfütze',
      'Ein Geruch von Kohl, der sich überall festsetzt',
      'Ein Kuchenbasar für ein Fußballturnier',
      'Eine Lüftung, die immer genau über einem Tisch zieht',
      'Kartoffelsalat mit zu viel Mayonnaise',
      'Frikadellen, bei denen man lieber nicht fragt',
      'Ein Eiscremeautomat, außer Betrieb',
      'Tomatensuppe aus der Tüte mit Croutons',
      'Pökelfleisch in Dosen',
      'Ein Tablett mit Tabletten – die Medikamentenausgabe liegt nebenan',
      'Ein Tisch, auf dem jemand ein Kartenhaus baut',
      'Ein Zettel am Kühlschrank: „Wer meinen Joghurt isst, stirbt“',
      'Lange Tische, an denen die Schichten streng getrennt sitzen',
      'Ein Kalender mit Geburtstagen der Crew',
      'Ein Hinweis zur Hygiene, halb abgerissen',
      'Hartgekochte Eier in einem Drahtkorb',
      'Eine Pfeffermühle, die sich nicht mehr drehen lässt',
      'Maisbrei mit künstlichem Butteraroma',
      'Ein Tablett, auf dem jemand sein Gebiss vergessen hat',
      'Eine Ecke mit Sitzsäcken, die nach Schweiß riechen',
      'Ein Aquarium mit einem einzelnen, fetten Goldfisch',
      'Ein Stapel Pappteller für den Notfall',
      'Ein Suppenkessel mit einer Kelle, die hineingefallen ist',
      'Eine lose Deckenplatte, durch die man in den Kabelschacht sieht',
      'Eine Kaffeekasse, in der mehr Schuldscheine als Münzen liegen',
      'Ein Nachtisch aus gefrorenem Fruchtsaft am Stiel',
      'Kaugummi unter jedem Tisch',
      'Ein Tischkalender mit Motivationssprüchen',
      'Eine Schüssel mit Plastikobst als Dekoration',
      'Das Brummen der Kühlaggregate, das nie aufhört',
    ],
  },
  {
    name: 'Konferenzraum',
    eintraege: [
      'Ein langer Tisch aus poliertem Kunstholz mit Kaffeeringen',
      'Ein Diaprojektor mit einem Magazin voller Dias',
      'Eine Leinwand, die sich nicht mehr ganz einrollen lässt',
      'Ein Whiteboard mit einer halb gelöschten Skizze eines Gangsystems',
      'Ein Flipchart mit der Überschrift „Schadensbegrenzung“',
      'Wasserkaraffen mit abgestandenem Wasser',
      'Ein riesiges Konzernlogo an der Stirnwand',
      'Ein Videobildschirm für Konferenzen mit mehreren Sekunden Verzögerung',
      'Ein Kristallaschenbecher, bis zum Rand voll',
      'Ein aufgeschlagenes Protokollbuch',
      'Eine Tagesordnung: „Punkt 4: Verluste“',
      'Namensschilder vor jedem Platz, eines fehlt',
      'Ein umgekippter Stuhl',
      'Eine Präsentation mit dem Titel „Quartalszahlen – vertraulich“',
      'Ein Modell der Kolonie unter einer Plexiglashaube',
      'Eine große Sektorkarte mit handschriftlichen Markierungen',
      'Eine kalte Kaffeekanne und Kondensmilchdöschen',
      'Ein Teller mit trockenen Keksen',
      'Ein Tischmikrofon mit rotem Aufnahmelicht',
      'Ein Tonbandgerät, das noch läuft',
      'Ein Panoramafenster mit Blick auf einen Staubsturm',
      'Halb geschlossene Jalousien, die Lichtstreifen auf den Tisch werfen',
      'Ein Zeigestock aus Teleskopmetall',
      'Karteikarten mit Stichpunkten für eine Rede',
      'Ein Stapel Verschwiegenheitserklärungen',
      'Verträge, die nur noch unterschrieben werden müssen',
      'Eine Anwesenheitsliste mit zwei fehlenden Unterschriften',
      'Ein teurer Füllfederhalter, den jemand liegengelassen hat',
      'Kugelschreiber mit Konzernlogo auf jedem Platz',
      'Eine Sitzordnung, bei der das Management auf gepolsterten Stühlen sitzt',
      'Ein Ölgemälde des Firmengründers, der streng herabblickt',
      'Ein Pokal für „Beste Kolonie des Jahres“',
      'Eine Konzernflagge in einem Ständer',
      'Eine Grünpflanze, die als einzige im Raum lebendig wirkt',
      'Eine Klimaanlage, die viel zu kalt eingestellt ist',
      'Notizblöcke voller Kritzeleien von Galgenmännchen',
      'Ein Evakuierungsplan an der Tür',
      'Folien für ein Sicherheitsbriefing auf einem Overheadprojektor',
      'Unscharfe Fotos von Verletzungen, verstreut auf dem Tisch',
      'Ein versiegelter Probenbehälter mitten auf dem Tisch',
      'Der Entwurf einer Pressemitteilung mit vielen Streichungen',
      'Ein Bericht, in dem ganze Absätze geschwärzt sind',
      'Eine Tafel mit Opferzahlen, die jemand schöngerechnet hat',
      'Ein Aktenkoffer mit Zahlenschloss',
      'Eine Kiste Mineralwasser von der Erde – nur für Gäste',
      'Ein Kalender mit dem Ankunftsdatum eines Inspektors',
      'Leere Plätze, die für „Beobachter“ reserviert sind',
      'Ein Telefon auf dem Tisch mit direkter Leitung zur Zentrale',
      'Eine Schachtel Zigarren für den Vorstand',
      'Eine Uhr mit drei Zeitzonen',
      'Eine Kamera in der Ecke, deren Lämpchen leuchtet',
      'Ein Rednerpult mit Konzernwappen',
      'Blätter mit Diagrammen von sinkenden Förderquoten',
      'Ein Stapel unbenutzter Notizblöcke, noch eingeschweißt',
      'Ein Schild an der Tür: „Besprechung – nicht stören“',
      'Ein Tisch, unter dem jemand einen Schuh verloren hat',
      'Ein Pappbecher mit Lippenstiftrand',
      'Eine Aktennotiz: „Mitarbeiter nicht informieren“',
      'Ein Stuhl mit einer Delle, als hätte jemand hineingeschlagen',
      'Eine Pinnwand mit Personalfotos und Pfeilen',
      'Ein Spesenbericht mit fragwürdigen Posten',
      'Ein Glas Wasser, in dem eine Tablette langsam zerfällt',
      'Eine Landkarte des Planeten mit einem neu eingezeichneten Sperrgebiet',
      'Ein Stapel Kündigungen, nach Abteilungen sortiert',
      'Eine Tabelle: „Kosten pro Kolonist“',
      'Ein Tischkalender mit dem Wort „Deadline“ in Rot',
      'Ein Schachspiel, mitten in der Partie stehengelassen',
      'Ein abgeschaltetes Konferenzterminal mit Nachricht im Speicher',
      'Ein Handzettel: „Wie spreche ich mit Angehörigen?“',
      'Eine Schale mit Pfefferminzbonbons',
      'Tischventilatoren an beiden Enden des Tisches',
      'Ein Stapel Luftfotos des Geländes',
      'Eine Wand voller Auszeichnungen und Zertifikate',
      'Ein Laserpointer, der nur noch schwach leuchtet',
      'Ein Tafellappen, der nach Kreide und Schweiß riecht',
      'Ein aufgeschlagener Vertrag mit Klausel 47 unterstrichen',
      'Ein Kassettenrekorder mit einer Beschwerde der Belegschaft',
      'Ein Tablett mit Sektgläsern für eine Feier, die nie stattfand',
      'Eine Notiz: „Wer hat die Genehmigung erteilt?“',
      'Eine Karte mit den Flugrouten der Versorgungsschiffe',
      'Ein Stuhl am Kopfende, der deutlich höher ist als alle anderen',
      'Ein Aufnahmeprotokoll, dessen letzte Minute gelöscht wurde',
      'Ein Handbuch zum Krisenmanagement mit Eselsohren',
      'Zwei Kaffeetassen, eine davon zerbrochen',
      'Ein Reißwolf in der Ecke, randvoll',
      'Ein Umschlag mit dem Stempel „Nur für den Vorstand“',
      'Ein Tischkärtchen mit einem durchgestrichenen Namen',
      'Eine Liste mit Schiffen, die keine Antwort mehr senden',
      'Ein vergessener Laborkittel über einer Stuhllehne',
      'Eine Box mit Taschentüchern',
      'Eine Wandtafel mit der Aufschrift „Ruhe bewahren“',
      'Eine Leinwand, auf der das Standbild eines verwackelten Videos eingefroren ist',
      'Eine Schreibmaschine mit einem eingespannten Blatt',
      'Ein Globus der Erde, an dem jemand Afrika abgekratzt hat',
      'Eine Fernbedienung ohne Batterien',
      'Eine Reservierungsliste für den Raum, voll bis nächsten Monat',
      'Ein Präsentationskoffer mit Mustern neuer Schutzanzüge',
      'Ein Ordner mit Versicherungsunterlagen für Crewmitglieder',
      'Eine Kaffeemaschine, die mitten in der Besprechung laut gurgelt',
      'Ein Summen aus den Lautsprechern, das niemand abstellen kann',
    ],
  },
  {
    name: 'Küche',
    eintraege: [
      'Ein Industrieherd mit sechs Gasflammen, von denen vier funktionieren',
      'Eine Fritteuse mit schwarzem, altem Öl',
      'Ein riesiger Mixer, groß genug für einen Arm',
      'Ein Messerblock, in dem ein Messer fehlt',
      'Ein Hackbeil, in ein Holzbrett geschlagen',
      'Ein Fleischwolf mit Kurbel',
      'Ein begehbarer Kühlraum mit schwerer Tür',
      'Eine Tiefkühlkammer, deren Thermometer minus zwei Grad anzeigt',
      'Riesige Konservendosen ohne Etikett',
      'Mehlsäcke mit dem Aufdruck „Notreserve“',
      'Ein Eimer Hefe, der vor sich hin blubbert',
      'Ein Gewürzregal, fast leer bis auf Salz und Paprika',
      'Ein Kanister Ketchup, zehn Liter',
      'Beutel mit Instantsuppenpulver',
      'Ein Sack Reis mit Mäusekot',
      'Eine Dose Eipulver, halb verbraucht',
      'Sojawürfel in großen Plastikbehältern',
      'Blöcke aus gepresstem Fleischersatz',
      'Ein echtes Steak, versteckt hinter den Konserven',
      'Kräuter in einem improvisierten Hydrokulturkasten',
      'Tomatenpflanzen unter einer UV-Lampe',
      'Eine laute Industriespülmaschine',
      'Ein Spülbecken voller fettiger Töpfe',
      'Ein verstopfter Abfluss mit stehendem Wasser',
      'Eine Mausefalle mit einem Käsestück darin',
      'Ein zerlesenes Kochbuch mit Soßenflecken',
      'Eine fleckige Schürze an einem Haken',
      'Topflappen mit Brandlöchern',
      'Ein Backofen, dessen Tür man mit dem Fuß zuhalten muss',
      'Eine Kaffeemaschine im Großformat',
      'Ein Servierwagen mit gestapelten Tabletts',
      'Ein Schneidebrett mit tiefen Kerben',
      'Handgeschriebene Rezeptkarten an der Wand',
      'Der Menüplan für die ganze Woche an einem Magnetbrett',
      'Ein Radio mit Klebeband an der Antenne',
      'Eine Abzugshaube, die kaum noch zieht',
      'Ein Feuerlöscher, dessen Plombe fehlt',
      'Brandsalbe im Erste-Hilfe-Kasten, fast aufgebraucht',
      'Gusseiserne Pfannen an einer Stange',
      'Ein großer Suppenkessel mit Resten',
      'Eine Kelle, so groß wie ein Unterarm',
      'Siebe in allen Größen',
      'Eine Reibe mit Hautresten',
      'Eine hydraulische Müllpresse',
      'Ein Müllschlucker, aus dem es rumort',
      'Ein Behälter mit Speiseresten für die Kompostanlage',
      'Ein Dampfgarer, der zischt und pfeift',
      'Ein Kühlschrank mit einem Vorhängeschloss',
      'Ein Zettel: „Chef isst hier nicht. Denkt drüber nach.“',
      'Eine Kiste mit frischen Zwiebeln – ein seltener Luxus',
      'Ein Nudelholz, das auch als Waffe taugt',
      'Ein Schrank mit hochprozentigem Kochwein',
      'Ein Eimer Bratfett',
      'Vorratsgläser mit eingemachtem Gemüse',
      'Eine Reihe Gewürzmühlen, alle leer',
      'Ein Wasserkocher mit Kalkablagerungen',
      'Ein Bräter mit angebranntem Boden',
      'Ein Kalender mit Lieferterminen des Versorgungsschiffs',
      'Eine Inventarliste mit vielen Fragezeichen',
      'Eine Dose Rattengift auf dem obersten Regal',
      'Eine Kiste mit Pilzkulturen zur Proteingewinnung',
      'Ein Fenster zur Kantine mit Durchreiche',
      'Ein Wandtelefon mit langem Spiralkabel',
      'Eine Knoblauchpresse',
      'Ein Waffeleisen, das nur zu besonderen Anlässen benutzt wird',
      'Eine Dose Kaffeebohnen, streng rationiert',
      'Ein Stapel Teller mit Rissen',
      'Ein Handbuch für die Wasseraufbereitung',
      'Eine Reihe von Messern, frisch geschliffen',
      'Ein Wetzstahl an einem Haken',
      'Eine Gemüsekiste mit keimenden Kartoffeln',
      'Eine Rolle Frischhaltefolie',
      'Eine offene Luke zum Lagerraum',
      'Ein Geruch nach verbranntem Fett, der überall hängt',
      'Eine Bratpfanne mit einer Delle',
      'Ein Nudelsieb auf dem Kopf eines Kochs',
      'Ein Tablett mit Schnittchen für den Vorstand',
      'Ein Stapel Brotlaibe aus Algenmehl',
      'Ein großer Eimer mit Kartoffelschalen',
      'Ein Thermometer im Kühlraum mit einer handschriftlichen Warnung',
      'Ein Kochtopf mit Deckel, der von innen klappert',
      'Pfefferschoten, die an einer Schnur trocknen',
      'Ein Schrank mit Putzmitteln neben den Lebensmitteln',
      'Eine Waage für Portionsgrößen',
      'Ein Behälter mit Eiswürfeln, die seltsam trüb sind',
      'Ein Handmixer mit abgebrochenem Quirl',
      'Ein Grill mit Fettspritzern an der Wand',
      'Ein Schneidebrett mit einem roten Fleck, der nicht abgeht',
      'Ein Korb mit Brotresten für den Pudding',
      'Ein Weinregal mit nur einer Flasche',
      'Ein Kupferkessel, der glänzt, als wäre er ein Heiligtum',
      'Ein Hinweis: „Kühlraum IMMER schließen!“',
      'Eine offene Mehltüte, von der eine Spur zur Wand führt',
      'Zwei Paar Gummistiefel neben der Tür',
      'Ein Kalender mit Pin-up-Motiven hinter dem Herd',
      'Eine Palette mit Konservendosen, die sich leicht wölben',
      'Ein Suppenwürfel-Vorrat für ein halbes Jahr',
      'Eine verbeulte Kaffeekanne aus Emaille',
      'Ein Fliegenfänger mit toten Insekten – woher kommen die?',
      'Ein Zapfhahn für Trinkwasser mit Rostgeschmack',
    ],
  },
  {
    name: 'Labor',
    eintraege: [
      'Ein Mikroskop mit einem Präparat, das noch eingelegt ist',
      'Eine Zentrifuge, die mit einem unwuchtigen Rumpeln ausläuft',
      'Ein Ständer mit beschrifteten Probenröhrchen, eines fehlt',
      'Petrischalen mit farbigen Bakterienkulturen',
      'Ein Brutschrank mit beschlagener Scheibe',
      'Ein Kühlschrank mit Biogefahr-Aufkleber',
      'Eine Handschuhbox mit einem Riss im Handschuh',
      'Ein Autoklav, der zischend Dampf ablässt',
      'Ein Laborkittel mit Blutspritzern am Ärmel',
      'Schutzbrillen an einem Wandhaken',
      'Pipetten in allen Größen',
      'Ein Bunsenbrenner mit kleiner blauer Flamme',
      'Eine Präzisionswaage unter einer Glashaube',
      'Ein Spektrometer mit einer endlosen Papierausgabe',
      'Röntgenbilder an einem Leuchtkasten',
      'Präparate in Gläsern mit trübem Formaldehyd',
      'Leere Tierkäfige mit offenen Türen',
      'Ein Käfig voller Laborratten, die ungewöhnlich still sind',
      'Ein Primatenkäfig mit verbogenen Gitterstäben',
      'Ein Sezierbesteck, sauber aufgereiht',
      'Ein Untersuchungstisch mit Fixierriemen',
      'Ein Kryobehälter mit Nebel am Deckel',
      'Ein Tank mit flüssigem Stickstoff',
      'Eine Notdusche mit einer Pfütze darunter',
      'Eine Augendusche an der Wand',
      'Eine Biogefahr-Tonne, randvoll',
      'Eine Dekontaminationsschleuse mit rotem Licht',
      'Ein Laborbuch mit hektischen letzten Einträgen',
      'Nummerierte Probenbehälter mit Schraubdeckeln',
      'Ein Fossil mit unbekannter Struktur',
      'Eine Gesteinsprobe, die sich leicht warm anfühlt',
      'Bodenproben in Plastiktüten',
      'Wasserproben mit Schwebeteilchen',
      'Eine Pflanzenprobe mit deutlichen Mutationen',
      'Ein Gensequenzierer mit ratterndem Drucker',
      'Eine Kultur, die über den Rand der Petrischale gewachsen ist',
      'Säure in einer braunen Glasflasche',
      'Ein Giftschrank mit Zahlenschloss',
      'Eine Gasmaske über einem Stuhl',
      'Eine Isolationszelle hinter dickem Panzerglas',
      'Ein Tonbandprotokoll: „Tag 14 der Beobachtung“',
      'Ein Monitor mit Vitalwerten – die Linie ist flach',
      'Eine Kamera auf einem Stativ, auf einen leeren Tisch gerichtet',
      'Ein Stapel Kaffeebecher neben dem Mikroskop',
      'Ein Whiteboard mit Strukturformeln und einem Fragezeichen',
      'Warnschilder: „Biologische Gefahrenstufe 3“',
      'Eine Zugangssperre mit Handflächenscanner',
      'Ein Probenbehälter, der von innen zerkratzt ist',
      'Eine Spritze mit einer schwarzen Flüssigkeit',
      'Ein Kühlschrank, dessen Tür nicht mehr schließt',
      'Eine zerbrochene Glasscheibe in einem Abzug',
      'Ein Abzug mit laufendem Gebläse',
      'Ein Mikroskopbild an der Wand: Zellen mit zu vielen Kernen',
      'Eine Liste mit Versuchsnummern und Todeszeiten',
      'Ein Tropf mit einer leeren Infusionsflasche',
      'Ein Brutkasten, in dem etwas geschlüpft ist',
      'Ein Gefäß mit einer Flüssigkeit, die sich durch den Boden frisst',
      'Ein Stapel Berichte mit Stempel „Direkt an die Zentrale“',
      'Ein Aquarium mit trübem Wasser und etwas, das sich bewegt',
      'Ein Laborhocker, der umgestoßen wurde',
      'Ein Handbuch zur Probenentnahme mit Randnotizen',
      'Ein Kittel mit Namensschild, sorgfältig aufgehängt',
      'Ein gesperrter Schrank mit der Aufschrift „Sonderprojekt“',
      'Ein Tablett mit Skalpellen, eines ist verbogen',
      'Eine Autopsieaufnahme auf einem Tonband',
      'Ein Behälter mit Säure-Brandspuren auf dem Tisch',
      'Eine Probe in einem Bernsteinharzblock',
      'Ein Aufkleber auf dem Terminal: „Daten nicht an die Crew weitergeben“',
      'Ein Messprotokoll mit ungewöhnlich hohen Werten',
      'Eine Uhr, die rückwärts zählt – ein Countdown',
      'Ein Kaffeefilter, der als Probenfilter benutzt wurde',
      'Eine Lupe mit Beleuchtung',
      'Ein Käfig mit einem Tier, das nicht von der Erde stammt',
      'Ein Behälter mit Eiern unbekannter Herkunft',
      'Ein tragbares Kühlgerät mit Konzernsiegel',
      'Ein Probenlabel: „Nicht öffnen – auf keinen Fall“',
      'Ein kaputtes Thermometer, Quecksilber auf dem Boden',
      'Ein Handschuh, der im Handschuhkasten festgeklebt ist',
      'Eine Ampulle mit einem Gegengift – oder was man dafür hält',
      'Ein Leuchtkasten mit einer Ultraschallaufnahme',
      'Ein Brustkorb-Röntgenbild mit einem dunklen Schatten',
      'Ein Behälter mit Zähnen, sortiert nach Größe',
      'Eine Zeichnung eines Lebenszyklus mit mehreren Stadien',
      'Ein Kalender mit täglichen Messungen, die abrupt enden',
      'Eine Notiz: „Probe wächst schneller als erwartet“',
      'Eine Kühlbox mit Blutkonserven',
      'Eine automatische Probenzuführung, die sich verklemmt hat',
      'Eine Kanne mit destilliertem Wasser',
      'Ein Tonbandgerät mit Diktaten eines Wissenschaftlers',
      'Eine Kiste mit Glaswaren, zur Hälfte zerbrochen',
      'Ein Verbandskasten mit einer benutzten Adrenalinspritze',
      'Ein Laborfenster mit Blick in einen dunklen Nebenraum',
      'Ein Mikrofon an der Isolierzelle für Befragungen',
      'Ein Tablett mit Nährlösung, grün schimmernd',
      'Zwei Stühle an einer Scheibe, als hätte man hier lange beobachtet',
      'Ein Handscanner, der ein unbekanntes Protein anzeigt',
      'Ein Behälter, der etwas zu schwer für seinen Inhalt ist',
      'Ein angebrannter Laborbericht im Papierkorb',
      'Ein Absperrband quer durch den Raum',
      'Der Geruch von Formaldehyd und etwas Süßlichem',
    ],
  },
  {
    name: 'Privatquartiere (Wohnräume)',
    eintraege: [
      'Eine ungemachte Koje mit zerknüllter Decke',
      'Ein Poster eines Sonnenuntergangs am Meer',
      'Ein Familienfoto, festgeklebt am Spiegel',
      'Ein Pin-up-Kalender an der Spindtür',
      'Eine Topfpflanze, liebevoll gepflegt',
      'Ein Tagebuch unter der Matratze',
      'Ein Berg schmutziger Wäsche',
      'Ein Spind mit Vorhängeschloss',
      'Ein Schlafsack auf dem Boden – das Bett wird nicht benutzt',
      'Ein Teddybär auf dem Kopfkissen',
      'Kinderspielzeug in einer Kiste',
      'Ein kleines Aquarium mit einem Guppy',
      'Ein Futternapf für eine Katze – aber keine Katze',
      'Eine Gitarre mit einer gerissenen Saite',
      'Hanteln unter dem Bett',
      'Ein Regal mit zerlesenen Taschenbüchern',
      'Eine Schuhschachtel voller Kassetten',
      'Ein Plattenspieler mit Jazzplatten',
      'Ein kleiner Fernseher mit Videorekorder',
      'Eine selbstgebaute Wasserpfeife',
      'Schnapsflaschen, im Lüftungsschacht versteckt',
      'Eine Pistole unter dem Kopfkissen',
      'Ein Bündel Briefe mit einem Band verschnürt',
      'Eine Strichliste an der Wand, Hunderte Striche',
      'Ein kleiner Hausaltar mit Kerzen und Heiligenbildern',
      'Räucherstäbchen in einer Konservendose',
      'Ein halb fertiges Schiffsmodell',
      'Ein halb gelegtes Puzzle einer Alpenlandschaft',
      'Kohlezeichnungen von Gesichtern an der Wand',
      'Eine Wandmalerei eines Waldes',
      'Ein Nachtlicht in Form eines Mondes',
      'Ein mechanischer Wecker mit zwei Glocken',
      'Ohrstöpsel und eine Schlafmaske',
      'Eine Batterie Medikamentendosen auf dem Nachttisch',
      'Eine frisch gebügelte Uniform auf einem Bügel',
      'Polierte Stiefel neben der Tür',
      'Eine enge Duschkabine mit Schimmel in den Fugen',
      'Ein Waschbecken mit Bartstoppeln',
      'Ein Spiegel mit einer Lippenstift-Nachricht: „Komm zurück“',
      'Bettwäsche mit Blümchenmuster',
      'Ein illegaler Heizlüfter',
      'Eine Kochplatte mit einem Topf Instantnudeln',
      'Ein Minikühlschrank voller Bier',
      'Eine Sammlung Kakteen auf der Fensterbank',
      'Ein Heimtrainer, als Kleiderständer benutzt',
      'Ein Boxsack an der Decke',
      'Eine Hängematte zwischen zwei Rohren',
      'Ein Aschenbecher auf dem Bett',
      'Eine Flagge des Heimatlandes an der Wand',
      'Ein Wandkalender mit dem Datum des Vertragsendes',
      'Eine Fotowand mit Bildern der Crew – ein Gesicht ist durchgestrichen',
      'Eine Duftkerze „Frühlingswiese“',
      'Eine Bibel auf dem Nachttisch',
      'Ein Stapel Pornohefte unter dem Bett',
      'Eine Schachtel mit Liebesbriefen von verschiedenen Absendern',
      'Ein Globus der Erde',
      'Ein Kinderbild: „Für Papa, komm bald heim“',
      'Ein Tonbandgerät mit Sprachnachrichten für die Familie',
      'Eine kaputte Brille auf dem Boden',
      'Ein Fenster mit Blick auf den Landeplatz',
      'Ein Bett mit ordentlich eingeschlagener Decke, militärisch exakt',
      'Ein Stapel Pizzaschachteln aus der Kantine',
      'Eine Sammlung von Schneekugeln',
      'Ein Baseballhandschuh und ein Ball',
      'Ein Fotoalbum mit Hochzeitsbildern',
      'Ein Nähkorb mit angefangener Stickerei',
      'Ein selbstgebautes Radio',
      'Ein gut verstecktes Messer in einer Matratzennaht',
      'Ein Stofftier eines Hundes, abgegriffen',
      'Eine Wand voller Konzernauszeichnungen',
      'Ein Schachbrett mit einer laufenden Fernpartie per Funk',
      'Eine Reisetasche, fertig gepackt',
      'Eine Liste mit Dingen, die man auf der Erde tun will',
      'Ein Raumspray gegen Schimmelgeruch',
      'Ein Heizkissen auf dem Bett',
      'Eine Sammlung Muscheln in einem Glas',
      'Ein Aquarell eines Bauernhofs',
      'Ein Poster einer Rockband',
      'Ein zerknülltes Bettlaken mit Blutflecken',
      'Ein Schrank voller identischer Overalls',
      'Eine Bürste mit langen Haaren',
      'Ein Schuhkarton mit Ersparnissen in bar',
      'Ein Hundehalsband ohne Hund',
      'Ein Kassettenrekorder, der ein Wiegenlied spielt',
      'Ein Stapel Briefe, alle an dieselbe Person, nie abgeschickt',
      'Ein Bilderrahmen ohne Bild',
      'Ein Loch in der Wand, mit einem Poster verdeckt',
      'Ein Tablett mit angetrocknetem Essen',
      'Eine Liste mit Medikamentendosen und Uhrzeiten',
      'Eine handgemalte Karte des Planeten',
      'Ein Rosenkranz um den Bettpfosten gewickelt',
      'Eine Sonnenlampe gegen Winterdepression',
      'Eine offene Schublade mit durchwühlter Unterwäsche',
      'Ein Dartpfeil, der in einem Foto des Vorgesetzten steckt',
      'Ein Paar Pantoffeln in Hasenform',
      'Eine verschlossene Kiste unter dem Bett',
      'Ein Lüftungsgitter, dessen Schrauben fehlen',
      'Ein Tagebuch, dessen letzter Eintrag mitten im Satz endet',
      'Ein Kissen mit einem aufgestickten „Zuhause“',
      'Die Wände sind mit Alufolie ausgekleidet',
    ],
  },
  {
    name: 'Schmierereien / Graffiti',
    eintraege: [
      '„DIE FIRMA LÜGT“',
      '„Wir sind nur Fracht“',
      'Eine lange Strichliste mit „Zähl die Tage“ darüber',
      '„Schicht C stinkt“',
      '„Rodriguez war hier – 2181“',
      '„Ich will nach Hause“',
      '„NICHT EINSCHLAFEN“',
      '„Sie hören mit“',
      '„Wo ist Team 3?“',
      '„Kein Signal seit 14 Tagen“',
      '„Gott hat diesen Ort verlassen“',
      '„Bezahlt uns endlich!“',
      '„STREIK“ in roter Farbe, darüber ein Konzernplakat geklebt',
      '„Nicht in die unteren Ebenen gehen“',
      '„Es ist in den Wänden“',
      '„Trau keinem Synthetischen“',
      '„Mama, es tut mir leid“',
      '„Filter wechseln, ihr Idioten“',
      '„TOT“ – in großen, verlaufenen Buchstaben',
      '„Wer das liest, ist doof“',
      '„Der Vorarbeiter ist ein Schwein“',
      'Ein Totenkopf mit dem Konzernlogo als Augen',
      'Eine Strichmännchen-Familie mit einem Haus und einer Sonne',
      'Ein Pfeil zu einem Lüftungsschacht und das Wort „NEIN“',
      'Blutige Handabdrücke, die nach unten verschmieren',
      'Ein Herz mit den Initialen „J + K“',
      'Die detaillierte Skizze eines Raumschiffs',
      'Eine obszöne Zeichnung mit dem Namen des Stationsleiters',
      'Ein Smiley mit viel zu vielen Zähnen',
      '„Hier gibt es nichts zu sehen“',
      '„Kolonie 7 wurde nicht evakuiert – sie wurde aufgegeben“',
      '„Jesus rettet – aber nicht hier“',
      '„Rauchen verboten“ – durchgestrichen, darunter „Leben verboten“',
      '„Wir sind nicht allein“',
      'Eine Liste mit Namen, die meisten durchgestrichen',
      '„Zur Hölle mit dem Vertrag“',
      '„Die Kinder zuerst!“',
      'Ein Pfeil: „Ausgang“ – der auf eine Wand zeigt',
      '„Ich hab es gesehen. Keiner glaubt mir.“',
      'Ein Galgenmännchen mit dem Wort „HILFE“',
      '„Zimmer 4B schuldet mir 50 Credits“',
      '„Kapitän Mendes ist ein Feigling“',
      '„Nie wieder Kälteschlaf“',
      '„Wir waren zuerst hier“',
      'Ein Schachbrettmuster über die ganze Wand',
      '„Tage bis zum Heimflug: 412“ – mehrfach korrigiert',
      '„Frag nicht, was in den Kisten ist“',
      '„Bleib im Licht“',
      '„Nachtschicht = Todesschicht“',
      '„Freiheit für die Äußeren Kolonien“',
      '„Hier hat Danny sein Frühstück verloren“',
      '„Achtung: Boden zu dünn“ – in Kreide',
      'Eine grobe Karte der Tunnel mit einem Kreuz',
      '„Ihr habt uns vergessen“',
      '„Die Marines kommen nicht“',
      '„Alles wird gut“ – mit einem Fragezeichen dahinter',
      '„Lüftungsschacht 12 NICHT ÖFFNEN“',
      'Eine Sonne, übermalt mit schwarzer Farbe',
      '„Ich höre es nachts kratzen“',
      '„Wer hat meinen Schraubenschlüssel?“',
      '„Liebe dich, Rosa“',
      'Eine Zeichnung eines Auges, das über der Tür wacht',
      '„Die Luft ist vergiftet – frag die Ärztin“',
      '„Profit vor Menschen“ – unterschrieben mit dem Konzernlogo',
      '„Frischfleisch“ – an der Tür der Neuankömmlinge',
      '„Keine Zeugen“',
      '„Die Toten reden über Funk“',
      'Ein Kreuz aus Klebeband mit einem Namen darunter',
      '„Nur noch drei Monate“',
      '„Rennt!“',
      '„Hier war einmal ein Garten“',
      '„Ich bin nicht verrückt“ – dutzendfach wiederholt',
      '„Grüße an die Erde – falls es sie noch gibt“',
      '„Frag nach Sektor 9“',
      'Die Zeichnung eines Wesens mit langem Kopf – schnell wieder übermalt',
      '„Hier wird nicht geweint“',
      '„Zahl oder stirb – Mack“',
      '„Das Wasser nicht trinken“',
      '„Wer den Alarm auslöst, ist schuld“',
      'Ein verblasstes Motivationsposter mit aufgemalten Hörnern',
      '„Ich will mein Geld zurück“',
      '„Letzter macht das Licht aus“',
      '„Fehlende Personen: 17“',
      '„Nicht den Aufzug nehmen“',
      '„Maschinen haben auch Gefühle“ – mit einem Herz daneben',
      '„Die Ärztin weiß Bescheid“',
      'Mit Fingernägeln in die Farbe gekratzte Linien',
      '„Gib auf“',
      '„SOS“ – mit Leuchtfarbe',
      '„Schichtleiter Novak kann mich mal“',
      '„Kein Weg raus“',
      '„Dieser Ort frisst Menschen“',
      '„Harper + Lee = Liebe“',
      '„Nicht zählen. Nie zählen.“',
      '„Es beobachtet uns durch die Kameras“',
      '„Der Konzern besitzt deine Seele – Seite 83 im Vertrag“',
      'Eine Zeichnung eines Mannes, der aus einem Fenster ins All fällt',
      '„Hier stand einmal ein Schild“',
      '„Was die Firma will, kriegt die Firma“',
      '„Morgen ist auch noch ein Tag. Vielleicht.“',
    ],
  },
  {
    name: 'Technik',
    eintraege: [
      'Ein Terminal mit Röhrenmonitor, der grüne Zeilen ausspuckt',
      'Ein Bewegungsscanner mit piependem Radar',
      'Ein Funkgerät, das auf einer alten Notfrequenz rauscht',
      'Eine Notfunkbake mit blinkender roter Leuchte',
      'Eine Sicherheitskamera, die sich langsam dreht',
      'Eine Türsteuerung mit herausgerissenem Bedienfeld',
      'Ein Kartenleser, der nur jede zweite Karte erkennt',
      'Ein Schweißgerät mit abgewickeltem Schlauch',
      'Ein Diagnosegerät mit einer langen Liste von Fehlercodes',
      'Ein offener Kabelbaum mit bunten Drähten',
      'Ein Sicherungskasten mit einer geschmolzenen Sicherung',
      'Ein Notstromgenerator, der stottert',
      'Eine Batteriebank mit Ladeanzeige bei 12 %',
      'Ein Kühlaggregat, das rhythmisch klopft',
      'Ein Luftaufbereiter, dessen Filter schwarz ist',
      'Ein CO₂-Wäscher mit Warnlampe',
      'Ein Wasserrecycler, der gurgelt',
      'Eine Steuerkonsole der Atmosphärenaufbereitung',
      'Eine Hydraulikpumpe, die Öl verliert',
      'Eine Druckschleuse mit Doppeltür',
      'Ein Laderoboter mit Greifarmen, der mitten im Gang stehengeblieben ist',
      'Ein Gabelstapler mit leerem Akku',
      'Ein Lastenaufzug mit Scherengitter',
      'Ein Deckenkran mit Fernbedienung am Kabel',
      'Ein Hebe-Exoskelett für schwere Lasten',
      'Ein Bohrgestänge, verklemmt im Gestein',
      'Ein Plasmaschneider mit Warnaufkleber',
      'Ein Magnetbandspeicher mit rotierenden Spulen',
      'Ein Nadeldrucker, der laut rattert',
      'Ein Oszilloskop mit einer seltsamen Wellenform',
      'Eine Funkantenne, die sich im Wind biegt',
      'Ein Radarschirm mit einem Punkt, der nicht da sein sollte',
      'Ein Seismograph, der leichte Erschütterungen aufzeichnet',
      'Eine Wetterstation mit einer Sturmwarnung',
      'Ein Strahlungsmessgerät mit ausschlagender Nadel',
      'Ein Wärmebildsensor, der einen kalten Fleck zeigt',
      'Eine Kälteschlafkammer mit beschlagenem Deckel',
      'Ein medizinischer Scanner mit einer Liege',
      'Ein automatisches Chirurgiesystem, nur für männliche Patienten kalibriert',
      'Ein Defibrillator, der sich auflädt',
      'Ein Beatmungsgerät, das gleichmäßig zischt',
      'Eine Infusionspumpe, die Alarm gibt',
      'Sprengladungen für den Bergbau in einer Kiste',
      'Ein Zünder mit Kabeltrommel',
      'Eine automatische Geschützstellung mit Munitionszähler',
      'Eine Aufklärungsdrohne mit gebrochenem Rotor',
      'Ein sechsrädriger Geländewagen mit Staub in den Filtern',
      'Ein Kettenfahrzeug mit Bohrkopf',
      'Eine Reaktorsteuerung mit Temperaturanzeige im gelben Bereich',
      'Brennstoffzellen in einem Wandregal',
      'Eine Solarzellenanlage, von Staub bedeckt',
      'Eine Windturbine, die in den Böen ächzt',
      'Eine Schwerlasttür, die sich nur halb öffnet',
      'Ein Notabschaltknopf unter einer Klappe',
      'Ein Schlüsselschalter für die Selbstzerstörungssequenz',
      'Ein Flugschreiber mit Brandspuren',
      'Ein Navigationscomputer mit veralteten Sternkarten',
      'Ein Transponder, der eine falsche Kennung sendet',
      'Ein Relaiskasten für Stationsfunk',
      'Eine Satellitenschüssel, die sich nicht mehr ausrichten lässt',
      'Ein Störsender, versteckt in einem Werkzeugkasten',
      'Eine Morsetaste für Notfälle',
      'Ein Fernschreiber mit endlosem Papierstreifen',
      'Ein Handscheinwerfer mit Tragegriff',
      'Eine rotierende Warnleuchte mit orangefarbenem Licht',
      'Eine Sirene, die nur noch jault',
      'Ein Lautsprecher mit Ansagen einer freundlichen Computerstimme',
      'Ein Lüftungsgebläse, das Staubflocken wirbelt',
      'Ein kleiner Wartungsroboter, der gegen eine Wand fährt',
      'Eine Vakuumpumpe mit rotem Druckmesser',
      'Ein Kompressor, der jede Minute anspringt',
      'Druckluftflaschen in einem Gestell',
      'Ein Wärmetauscher mit heißen Rohren',
      'Ein Thermostat, das auf 29 Grad klemmt',
      'Ein Staubfilter, verstopft mit rotem Sand',
      'Eine Kommunikationskonsole mit Kopfhörern',
      'Ein Hauptrechner mit Blinklichtern und Lochkarten',
      'Ein Bandlaufwerk mit den Sicherheitsprotokollen',
      'Ein Sensorturm auf dem Dach mit abgebrochener Spitze',
      'Ein Lichtschalter, der Funken schlägt',
      'Ein Notbeleuchtungssystem in rotem Licht',
      'Ein Kontrollpult mit Kippschaltern und Leuchtknöpfen',
      'Eine Wasserpumpe mit ausgeleiertem Keilriemen',
      'Ein Plasmaschweißroboter an einer Schiene',
      'Ein Heizelement, das glühend rot leuchtet',
      'Eine Gegensprechanlage mit Kurbelinduktor',
      'Ein tragbarer Generator auf Rädern',
      'Ein Datenterminal mit Ledersitz und Kopfhörern',
      'Ein Frachtscanner an der Schleuse',
      'Ein Tauchpumpenkasten in einer überfluteten Ebene',
      'Ein Sauerstofftank mit leckendem Ventil',
      'Eine Kabeltrommel mit hundert Metern Starkstromkabel',
      'Eine Stationsuhr mit Ziffern aus Leuchtröhren',
      'Ein Bildtelefon mit Verzögerung und Schneegestöber',
      'Ein Taschenrechner-Computer mit Magnetkarten',
      'Ein Kurzstreckensender in einem Rucksack',
      'Eine Leuchtbake auf einem Landefeld',
      'Ein Messgerät für Gaskonzentration mit Piepton',
      'Ein Aufzugsmotor, der schwer brummt',
      'Ein altes Robotermodell, abgeschaltet in einem Schrank',
    ],
  },
];
